### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by NunweilerK** [planbcoding/vscode-react-refactor#12]
I've highlighted some code in a .jsx file but I see no lightbulb. Hitting Ctrl+. gives the message "No code actions available". Am I doing something wrong or is there anything else I could try?

**Comment by andrewhuszar** [comment]
Hi,
Probably it's related to parsing error (something in the selected JSX). From 1.1.0 we display the error message coming from the Parser. Give it another try! Also, check Debug instructions in the Readme.
